### ISSUE TITLE
Parent-Child-Relation between Exercises

### ISSUE THREAD

**Issue by JoramStiel** [wienans/quadcoach#12]
Often you will have variations of an exercise, so that the level would be increase. The idea is now that you would first create the lowest level of exercise and then create new exercise as child of them. So that we could show the childs and parent of exercise on the exercise page.

**Comment by wienans** [comment]
Wouldn’t call it parent child but rather more general „related“

**Comment by JoramStiel** [comment]
yeah, will I wrote it  here I had the same thought. Advantage of parent child relation would be that you could see what is the first exercise 🤔

**Comment by wienans** [comment]
Each Exercise now can have Related Exercises
