### ISSUE TITLE
Implement createApi from redux-toolkit for easy API handling inside frontend

### ISSUE THREAD

**Issue by JoramStiel** [wienans/quadcoach#16]
- using createApi from https://redux-toolkit.js.org/rtk-query/api/createApi provides functionality for easy handling while data is loading, if an error occurs and provides a good Coaching system
- create for our API one base using an axios base Implementation and include it to redux store
- in every place we have api calls create an api file, in which endpoints are injected to api Base
- axios is some library for doing api calls with some usefull functions

**Comment by wienans** [comment]
Finished with #31
