### ISSUE TITLE
Convert client project to Typescript

### ISSUE THREAD

**Issue by JoramStiel** [wienans/quadcoach#17]
- transform project to typescript by creating new project with vite react typescript and then copy file and rename them to ts
- fix all problems and add types

**Comment by JoramStiel** [comment]
Look inside draft pr #18 for current state

**Comment by wienans** [comment]
Added client dockerfile again and installed dependencies. System can boot even if code is not strictly typescript

**Comment by wienans** [comment]
next PR was #30

**Comment by wienans** [comment]
Conversion done
