### ISSUE TITLE
Fix template design

### ISSUE THREAD

**Issue by wienans** [wienans/quadcoach#6]
- make sidenav (drawer) always temporary (hovering over content)
- delete search bar in the top
- komment out or leave dependent on effort buttons in the nav bar we migh need in the future (will be then without function)
- move the drawer button from the right to the left?

**Comment by JoramStiel** [comment]
I think we could leave search bar in top and implement a global search. Currently we provide there only exercise search, but in future we might search whatever. So current a search result would provide to jump to exercise.

**Comment by wienans** [comment]
Good idea with the search bar

**Comment by wienans** [comment]
Should we remove notification bell? I don’t see some useful interaction with it

**Comment by JoramStiel** [comment]
yeah, delete or comment it out for now.
Currently I would think about notifications: 
- your exercise has been updated
- If we do multilanguage: someone added new language 
- If we would implement some following mechanism: User A posted new exercise
- for trainings: Training needs to bei planned, upcomming trainings

**Comment by wienans** [comment]
- i don’t see the thing about you need to plan Training because it is not a phone app it does not send notifications, it does not make sense to have any time based notifications to create or use something.
- other things are potentially possible but not sure if we develop in this direction. And if gar in the future. Will comment / remove it
